spring:
  profiles:
    active: smart
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://host.docker.internal:1433;databaseName=hr;
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
thymeleaf:
  cache: false

mvc:
  format:
    date-time: yyyy-MM-dd HH:mm:ss

hr:
  salary:
    years:
      year1: 2.5
      year2: 5
      year3: 10
    percent:
      percent1: 0
      percent2: 2
      percent3: 5
      percent4: 10